# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

variables:
  PRISMA_API_URL: https://api4.prismacloud.io
  PRISMA_REPO: amb224/Test_Azure_pipelines/casdemo

jobs:
- job: Prisma_Cloud_Job
  displayName: Prisma Cloud Job
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
    displayName: 'Use Python 3.8'
  - script: pip install checkov
    displayName: Install Checkov
  - script: checkov --directory . --use-enforcement-rules --bc-api-key $(PRISMA_KEY) --repo-id $(PRISMA_REPO) --branch master 
    displayName: Run Checkov

